#pragma once
#include "DebugSystem.h"
#include "AddBoidsMessage.h"
#include "PlayerMoveToMessage.h"
#include "AddUnitMessage.h"
#include "RemoveRandUnitMessage.h"
#include "QuitGameMessage.h"
#include "IncreaseDebugValueMessage.h"
#include "SetDebugModeMessage.h"